### ISSUE TITLE
calculon console throws: AttributeError: 'NoneType' object has no attribute 'core'

### ISSUE THREAD

**Issue by unfo** [snare/calculon#36]
Fresh git pull, calculon display works fine, but console fails with:

```
$ calculon console
Traceback (most recent call last):
  File "/usr/local/bin/calculon", line 9, in <module>
    load_entry_point('calculon==0.1', 'console_scripts', 'calculon')()
  File "/Library/Python/2.7/site-packages/calculon-0.1-py2.7.egg/calculon/main.py", line 78, in main
    args.func()
  File "/Library/Python/2.7/site-packages/calculon-0.1-py2.7.egg/calculon/main.py", line 50, in console
    calculon.V = VoltronProxy()
  File "/Library/Python/2.7/site-packages/calculon-0.1-py2.7.egg/calculon/voltron_integration.py", line 45, in __init__
    self.connect()
  File "/Library/Python/2.7/site-packages/calculon-0.1-py2.7.egg/calculon/voltron_integration.py", line 103, in connect
    raise e
AttributeError: 'NoneType' object has no attribute 'core'
```

**Comment by snare** [comment]
Should be fixed in deed0886ea6e49cae1fb51a7ebfd0ef5dc70e3ca

**Comment by unfo** [comment]
Confirmed working.

**Comment by snare** [comment]
Great thanks.
