### ISSUE TITLE
Pyro4.errors.PyroError: invalid uri

### ISSUE THREAD

**Issue by Tyilo** [snare/calculon#37]
Fresh install of calculon from master branch:

```
$ calculon
usage: calculon [-h] {display,console} ...
calculon: error: too few arguments
$ calculon console
Failed to connect to display
Python 2.7.9 (default, Dec 15 2014, 10:01:34)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 1+1
2
Traceback (most recent call last):
  File "/usr/local/bin/calculon", line 9, in <module>
    load_entry_point('calculon==0.1', 'console_scripts', 'calculon')()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/calculon-0.1-py2.7.egg/calculon/main.py", line 82, in main
    args.func()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/calculon-0.1-py2.7.egg/calculon/main.py", line 59, in console
    code.interact(local=locals())
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/code.py", line 306, in interact
    console.interact(banner)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/code.py", line 243, in interact
    more = self.push(line)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/code.py", line 265, in push
    more = self.runsource(source, self.filename)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/calculon-0.1-py2.7.egg/calculon/repl.py", line 155, in runsource
    calculon.disp = Pyro4.Proxy(ENV['uri'])
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 192, in __init__
    uri = URI(uri)
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 58, in __init__
    raise errors.PyroError("invalid uri")
Pyro4.errors.PyroError: invalid uri
```

**Comment by snare** [comment]
Does this happen every time? Exit the display and launch it again? Make sure you launch the display before the console.

**Comment by Tyilo** [comment]
I forgot to launch the display as I haven't used calculon since it was just a console.
Sorry.

**Comment by snare** [comment]
No worries. I'll get back to implementing the integrated mode again one day :)
